export const theme = {
  colors: {
    background: "black",
    backgroundImg: "",
    primary: "#007BFF",
    card: "black",
    text: "#eefcfc",
    border: "gray",
    notification: "white",
    textSecondary: "#cccccc",
    error: "#FF5555",
    buttonText: "black",
    popupBackground: "white",
    "bg-grey": "#2C2C2C",
    "border-grey": "#383838",
    "text-grey1": "#B3B3B3",
    "text-grey2": "#F3F3F3",
    "text-grey3": "#F5F5F5",
    "bg-green": "#14AE5C",
    "bg-blue": "#0055FF",
    "bg-header": "black",
    "light-blue": "#00c9c8",
    "dark-green": "#1B8C10",
  },
  fonts: {
    primary: "space-grotesk",
    primaryBold: "space-grotesk-semibold",
    primaryMedium: "space-grotesk-medium",
    secondary: "inter",
  },
};
